services:
  - type: web
    name: n8n
    env: docker
    image:
      url: n8nio/n8n:latest
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: WEBHOOK_URL
        value: https://your-n8n-app.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: abcLongvu12101986@@@
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: TZ
        value: America/Sao_Paulo
      - key: N8N_LOG_LEVEL
        value: info
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 168
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none
      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
        value: false
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: false
